### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by hooperbloob** [HolgerHees/smartserver#1]
I love this project, just what I was looking for.  A couple of suggestions:

It would be great to have some kind of tree/graph showing the various dependencies of the various subsystems.  Then users could known which parts could be safely dropped or modified without side effects.

An overview of how Vagrant and Ansible interact to build out the system would help us understand how it all comes together.

Provide some simple FAQ/tutorial sections, something like:

-   How to add a printer/device
-   How to add a new category in the top heading

**Comment by HolgerHees** [comment]
Nice to know that it is useful for other people too. :-)

My long term plan is to provide all of that.

I will add some dependency comments inside server.yml as comments too.

And I already tried to move all non necessary/optional roles to config/demo/roles.yml to make it easy to modify it to your needs without modifying the main server.yml. Means the idea is that all individual modifications should happen only inside your config folder. This makes it easy to sync your branch from time to time with the main branch or work without any individual branch. 

Maybe I will move the "cron_backup_rsync" role also to the individual role config, because it is also not necessary for the main deployment.

To add your individual categories just edit "webui_urls" inside config/demo/env.yml. But currently this will not work for top headings. Just for sub entries in the category cameras and devices. To make this more flexible I will refactor some parts here too soon.

So my next steps will be

1. Try to finish travisCI testing
2. Add dependency comments
3. Maybe move "cron_backup_rsync" to the individual role config
4. Document more and add some tutorioals / FAQ's

btw. My personal main OS is suse. So only this is used in a production environment and well tested. Fedora is only tested inside a virtual machine. I created it only to convince more people using this deployment project who don't want to use suse. I was also thinking about ubuntu sometimes. So, I would be happy about feedback/suggestions/bugfixes from people using fedora in a production environment.

To answer your question regarding a printer or other device. You can modify the proxy role (config/demo/roles/apache_proxy/templates/etc/apache2/_.ansible.conf.d/proxy.conf) and add a reverse proxy to your devices. As an additional step add this reverse proxy url to "webui_urls" inside config/demo/env.yml to make it available inside the webui below the devices section.

**Comment by hooperbloob** [comment]
Since all the various entries under the roles directory relate to your home configuration, is there a way to leave those in place and reference just a subset of them in my config?  I don't have a Roomba, MySQL, Kibana, etc.   I could then add new ones in the same place that won't affect you.

**Comment by HolgerHees** [comment]
currently the project contains mandatory roles and optional roles.

all optional roles are included inside your custom config folder like "/config/demo/roles.yml" so you can disable/remove everything what you want here. You can also include your own rules here like I do in with the "/config/demo/roles/apache_proxy/" role.

currently optional roles are openvpn_cloud, cloudsync, alexa, roomba, vcontrold and the proxy role.

all other roles are more or less mandatory. You can disable it inside the main server.yml file, but then you have to handle a lot of dependency issues because they are necessary for a lot of other services. (i will document it later). Also that you have to modify a file outside the config folder makes it more difficult to merge upcoming changes back to your branch.

Currently nextcloud and openhab are a central part of this deployment and both depends on mysql.

Also kibana is used as the visualization ui for the central logging. (currently documented in the wiki)

The last week I refactored the way how menu entries are registered in the webui. The different roles are now responsible to provide and register a menu entry. That means if you disable a role. The related menu entry is gone from the webui.

It is also much easier now to register your own custom menu entries. (will also be documented soon). As an example how this works, you can check the folder "/config/demo/roles/apache_proxy/templates/webui/"

**Comment by HolgerHees** [comment]
Check https://github.com/HolgerHees/smartserver/wiki for the documentation.
