### ISSUE TITLE
Need some way to handle self-signed certs in demo mode

### ISSUE THREAD

**Issue by hooperbloob** [HolgerHees/smartserver#4]
Recent browser updates are not allowing self-signed certs to be accepted and there doesn't seem to be any good instructions on how to overcome this.  Two possible approaches:

1) provide step-by-step instructions on how to configure the latest releases of Firefox/Chrome to accept self-signed certs from Smartserver.

or 

2) provide a mode switch in Smartserver to allow it to operate without self-signed certificates.

I really hope this can be fixed, I'd like to start developing with Smartserver.

**Comment by HolgerHees** [comment]
what is the exact error message?

The only problem I know is that it is not possible to accept the certificates for all subdomains from inside the webui, because the webui is using iframes and the browser does not allow accepting certificates inside an iframe.

So can you try to open each individual subdomain directly in your browser and accept it there.

**Comment by hooperbloob** [comment]
In latest Firefox:

"openhab.smartserver.test uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. 
 Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT"

Ok, just tried https://openhab.smartserver.test  and was able to accept the cert.
Thanks, I would suggest mentioning this issue & workaround in the docs.

**Comment by HolgerHees** [comment]
is updatet

https://github.com/HolgerHees/smartserver/wiki/Setup
